#!/usr/bin/env bash
# scaffold-test.sh — scaffold a bundled bats test stub for each newly created
# plugin script. /edit-plugin runs this after applying an edit that adds a new
# top-level scripts/*.sh: it writes <plugin-dir>/scripts/tests/<name>.bats — a
# BUNDLED test inside the plugin's own directory (never the marketplace's
# centralized scripts/tests/, which is out of bounds for /edit-plugin), so
# verify-repo.sh's HARD bundled-tests check then covers the new script.
#
# It is idempotent: an existing test file (scaffolded before, or hand-written) is
# left untouched. Only a top-level scripts/*.sh is scaffolded — a nested path
# like scripts/lib/foo.sh is skipped with a note (mirroring verify-repo.sh's own
# centralized-test scope). A path whose script does not exist under <plugin-dir>
# is reported as an error (non-zero exit) but does NOT stop the remaining paths
# from being processed.
#
# Usage: scaffold-test.sh <plugin-dir> <script-path>...
#   <script-path>... are new-script paths from the edit plan's files[]
#   (plugin-relative, ./-prefixed, or plugin-dir-prefixed — all normalized).
set -euo pipefail

die() {
  printf 'scaffold-test: %s\n' "$*" >&2
  exit 1
}

plugin_dir="${1:?usage: scaffold-test.sh <plugin-dir> <script-path>...}"
shift
plugin_dir="${plugin_dir%/}"
[[ -d "$plugin_dir" ]] || die "plugin directory not found: $plugin_dir"
[[ "$#" -gt 0 ]] || die "no script paths given"

status=0

# Normalize a plan file path to plugin-relative form (strip a leading ./, and a
# leading <plugin-dir>/ or <basename>/ prefix) — identical to verify-repo.sh, so
# scripts/foo.sh, ./scripts/foo.sh and plugins/<name>/scripts/foo.sh all match.
norm_rel() {
  local p="${1#./}" pd="${plugin_dir#./}"
  p="${p#"$pd"/}"
  p="${p#"$(basename "$plugin_dir")"/}"
  printf '%s' "$p"
}

for arg in "$@"; do
  [[ -n "$arg" ]] || continue
  rel="$(norm_rel "$arg")"
  case "$rel" in
    scripts/*/*)
      printf 'scaffold-test: %s is not a top-level scripts/*.sh — skipping\n' "$rel"
      continue
      ;;
    scripts/*.sh) ;;
    *)
      printf 'scaffold-test: %s is not a scripts/*.sh path — skipping\n' "$rel"
      continue
      ;;
  esac

  if [[ ! -f "$plugin_dir/$rel" ]]; then
    printf 'scaffold-test: script not found: %s\n' "$plugin_dir/$rel" >&2
    status=1
    continue
  fi

  name="$(basename "$rel" .sh)"
  test_file="$plugin_dir/scripts/tests/$name.bats"
  if [[ -e "$test_file" ]]; then
    printf 'scaffold-test: %s already exists — leaving it untouched\n' "$test_file"
    continue
  fi

  mkdir -p "$plugin_dir/scripts/tests"
  cat >"$test_file" <<EOF
#!/usr/bin/env bats
#
# SCAFFOLDED STUB for scripts/$name.sh — replace the smoke @test below with real,
# script-specific assertions. Generated by plugin-editor/scaffold-test.sh.

setup() {
  # This stub lives in <plugin>/scripts/tests/; the script under test is its
  # sibling one level up, in <plugin>/scripts/.
  SCRIPT="\$(cd "\$(dirname "\$BATS_TEST_FILENAME")/.." && pwd)/$name.sh"
}

@test "$name.sh runs and produces output" {
  command -v bats >/dev/null 2>&1 || skip "bats not installed"
  [[ -x "\$SCRIPT" ]] || skip "scripts/$name.sh is not executable"
  # TODO: replace with a real, script-specific assertion.
  run "\$SCRIPT"
  [ -n "\$output" ]
}
EOF
  printf 'scaffold-test: wrote %s\n' "$test_file"
done

exit "$status"
