#!/usr/bin/env bash
# scaffold-test.sh — scaffold a bundled bats test stub for each newly created
# plugin script. /edit-plugin runs this after applying an edit that adds a new
# top-level scripts/*.sh: it writes <plugin-dir>/scripts/tests/<name>.bats — a
# BUNDLED test inside the plugin's own directory (never the marketplace's
# centralized scripts/tests/, which is out of bounds for /edit-plugin), so
# verify-repo.sh's HARD bundled-tests check then covers the new script.
#
# It is idempotent: an existing test file (scaffolded before, or hand-written) is
# left untouched. Only a top-level scripts/*.sh is scaffolded — a nested path
# like scripts/lib/foo.sh is skipped with a note (mirroring verify-repo.sh's own
# centralized-test scope). A path whose script does not exist under <plugin-dir>
# is reported as an error (non-zero exit) but does NOT stop the remaining paths
# from being processed.
#
# Usage: scaffold-test.sh <plugin-dir> <script-path>...
#   <script-path>... are new-script paths from the edit plan's files[]
#   (plugin-relative, ./-prefixed, or plugin-dir-prefixed — all normalized).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source-path=SCRIPTDIR
# shellcheck source=lib/plan-paths.sh
. "$SCRIPT_DIR/lib/plan-paths.sh"

die() {
  printf 'scaffold-test: %s\n' "$*" >&2
  exit 1
}

plugin_dir="${1:?usage: scaffold-test.sh <plugin-dir> <script-path>...}"
shift
plugin_dir="${plugin_dir%/}"
[[ -d "$plugin_dir" ]] || die "plugin directory not found: $plugin_dir"
[[ "$#" -gt 0 ]] || die "no script paths given"

status=0

# norm_rel (plan-path normalization) is shared with verify-repo.sh via
# lib/plan-paths.sh, sourced above.

for arg in "$@"; do
  [[ -n "$arg" ]] || continue
  rel="$(norm_rel "$plugin_dir" "$arg")"
  case "$rel" in
    scripts/*/*)
      printf 'scaffold-test: %s is not a top-level scripts/*.sh — skipping\n' "$rel"
      continue
      ;;
    scripts/*.sh) ;;
    *)
      printf 'scaffold-test: %s is not a scripts/*.sh path — skipping\n' "$rel"
      continue
      ;;
  esac

  if [[ ! -f "$plugin_dir/$rel" ]]; then
    printf 'scaffold-test: script not found: %s\n' "$plugin_dir/$rel" >&2
    status=1
    continue
  fi

  name="$(basename "$rel" .sh)"
  test_file="$plugin_dir/scripts/tests/$name.bats"
  if [[ -e "$test_file" ]]; then
    printf 'scaffold-test: %s already exists — leaving it untouched\n' "$test_file"
    continue
  fi

  mkdir -p "$plugin_dir/scripts/tests"
  cat >"$test_file" <<EOF
#!/usr/bin/env bats
#
# SCAFFOLDED STUB for scripts/$name.sh — a placeholder so the new script has a
# bundled test file (which verify-repo.sh discovers). It is intentionally SKIPPED
# rather than exercising the script: replace it with real assertions, then remove
# the \`skip\`. Generated by plugin-editor/scaffold-test.sh.
#
# It does NOT invoke scripts/$name.sh — an auto-generated no-argument run could
# hang (a script that reads stdin) or fire a side effect, and a bare smoke
# assertion would wrongly fail a legitimately-silent script under verify-repo.sh's
# HARD bundled-tests check. Write assertions that match what the script does.

setup() {
  # The script under test is a sibling one level up, in <plugin>/scripts/.
  SCRIPT="\$(cd "\$(dirname "\$BATS_TEST_FILENAME")/.." && pwd)/$name.sh"
}

@test "scripts/$name.sh has tests" {
  # Write real assertions for "\$SCRIPT" — for example:
  #   run "\$SCRIPT" --help
  #   [ "\$status" -eq 0 ]
  skip "scaffolded placeholder — add real tests for scripts/$name.sh, then remove this skip"
}
EOF
  printf 'scaffold-test: wrote %s\n' "$test_file"
done

exit "$status"
